coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        only_pulls: true
        if_ci_failed: success

    patch:
      default:
        target: 80%
        threshold: 1%
        only_pulls: true
        if_ci_failed: success
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false