baseURL = 'https://antch57.github.io/quest/'
locale = 'en-us'
title = 'quest docs'

[params]
  BookTheme = 'auto'
  BookSection = 'posts'
  BookRepo = 'https://github.com/antch57/quest'

[module]
[[module.imports]]
  path = 'github.com/alex-shpak/hugo-book'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
