# ci - runs tests and linters on every push and pull request to main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

name: ci

jobs:
  lint:
    runs-on: ubuntu-slim
    steps:
      - name: checkout repo
        uses: actions/checkout@v6

      - name: setup go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'

      - name: run gofmt
        run: |
          out="$(gofmt -l .)"
          if [ -n "$out" ]; then
            echo "$out"
            echo "gofmt failed... re-run on local ya goof"
            exit 1
          fi

      - name: run vet
        run: go vet ./...

  test:
    runs-on: ubuntu-slim
    steps:
      - name: checkout repo
        uses: actions/checkout@v6

      - name: setup go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'

      - name: download dependencies
        run: |
          go mod download
          go version

      - name: run tests
        run: |
          go test -v -coverprofile=coverage.txt -covermode=atomic ./...
          go tool cover -func=coverage.txt

      - name: upload coverage reports to codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
